[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"
[tool.semantic_release]
version_variables = ["pyproject.toml:version"]
build_command = "python -m build"
commit_parser = "scipy"